# this is used to create new deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy-nginx
  labels:
    env: demo
    type: rs
spec: 
  template:
    metadata:
      name: yamlpod
      labels:
        env: demo
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
        ports:
          - containerPort: 80
  replicas: 3
  selector:
    matchLabels:
      env: demo