# this is used to create replica Set
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nginx
  labels:
    env: demo
    type: rs
spec: 
  template:
    metadata:
      name: yamlpod
      labels:
        env: demo
    spec:
      containers:
      - name: nginxcontainer
        image: nginx
  replicas: 3
  selector:
    matchLabels:
      env: demo